import type { Metadata } from "next";
import { Barriecito } from "next/font/google";
import "./globals.css";

const barriecito = Barriecito({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-barriecito',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body  > {/*className={ barriecito.variable }*/}
        {children}
      </body>
    </html>
  );
}
